# Generated by Django 2.2.7 on 2019-11-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
                ('noHistoriaClinica', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PAnciano',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Paciente')),
                ('tieneDieta', models.BooleanField(default=False)),
            ],
            bases=('main.paciente',),
        ),
        migrations.CreateModel(
            name='PJoven',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Paciente')),
                ('fumador', models.BooleanField(default=False)),
                ('noAñosFumando', models.IntegerField()),
            ],
            bases=('main.paciente',),
        ),
        migrations.CreateModel(
            name='PNinno',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Paciente')),
                ('peso', models.IntegerField()),
                ('estatura', models.IntegerField()),
            ],
            bases=('main.paciente',),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Estado')),
                ('tipoConsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoConsulta')),
            ],
        ),
    ]
