# Generated by Django 2.2.7 on 2019-11-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cantPaciente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombreEspecialista',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
